apiVersion: v1
kind: Pod
metadata:
  labels:
    run: rohan-1
  name: rohan-1
spec:
  containers:
  - image: nginx
    name: rohan-1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
